export const RABBITMQ_APPENDER_CONNECTION = Symbol('RABBITMQ_APPENDER_CONNECTION');
export const RABBITMQ_APPENDER_PRODUCER = Symbol('RABBITMQ_APPENDER_PRODUCER');
export const RABBITMQ_APPENDER_OPTIONS = Symbol('RABBITMQ_APPENDER_OPTIONS');
