export const RABBITMQ_APPENDER_CONNECTION_TOKEN = Symbol('RABBITMQ_APPENDER_CONNECTION_TOKEN');
export const RABBITMQ_APPENDER_PRODUCER_TOKEN = Symbol('RABBITMQ_APPENDER_PRODUCER_TOKEN');
export const RABBITMQ_APPENDER_OPTIONS_TOKEN = Symbol('RABBITMQ_APPENDER_OPTIONS_TOKEN');
